"""The HTML review view: generated by the run, self-contained, escaped, linked to its source files."""

import json
import re
import unittest
from pathlib import Path

from agent.processing.brief import TemplateProvider
from agent.run_playbook import run
from tests.helpers import tempdir

MOTION = Path(__file__).resolve().parent.parent / "playbooks/motions/reign-first-motion.jsonc"


class ReviewViewTests(unittest.TestCase):
    def test_run_writes_self_contained_linked_review(self):
        with tempdir() as d:
            s = run(MOTION, Path(d), provider=TemplateProvider())
            page = Path(s["review"]).read_text()
            self.assertNotRegex(page, r"<script|<link|src=|@import|url\(")
            for href in re.findall(r'href="([^"]+)"', page):
                self.assertTrue((Path(s["review"]).parent / href).resolve().exists(), href)
            self.assertIn("OFFLINE TEST MODE", page)
            self.assertIn("22/22", page)
            self.assertIn("hs-1007", page)  # the watched hospital, with its reason

    def test_record_text_is_escaped(self):
        from agent.output.review import render
        with tempdir() as d:
            run_dir = Path(d) / "runs" / "r1"
            (run_dir / "briefs").mkdir(parents=True)
            (run_dir / "briefs" / "x.md").write_text("<img src=x onerror=alert(1)>")
            audit = Path(d) / "audit.jsonl"
            audit.write_text(json.dumps({"run_id": "r1", "action": "score", "object": "<b>o</b>", "principal": "P Q",
                                         "send": False, "purpose": "<script>x</script>", "detail": {}}) + "\n")
            page = render(run_dir, audit_path=audit, errors_path=Path(d) / "errors.jsonl")
            self.assertNotIn("<img src=x", page)
            self.assertNotIn("<script>", page)


if __name__ == "__main__":
    unittest.main()
